#!/usr/bin/env bash
# Configures a new ubuntu machine by installing
# Nginx where it should be listening on port 80
# Serve a page that would return a Hello World string
#

sudo apt-get update
sudo apt-get install nginx -y
echo "Hello World!" > sudo /var/www/html/index.nginx-debian.html
sudo service nginx start

