#!/bin/bash

sed -i 's/listen [::]:80 default_server;/listen 80 default_server;/g' /etc/nginx/nginx.conf
systemctl restart nginx
sleep 2
systemctl is-active --quiet nginx || echo "nginx is not running"
