#!/usr/bin/env bash
# will display "To infinity and beyond" indefinitely with
# a sleep 2 in between each iteration.
# it will also display "I am invincible!!!" in between each iteration throughout the operation
while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM 
done
