#!/usr/bin/env bash
# By : Muzzo
# This configures an Ubuntu server as follows:
# for localhost resolves to 127.0.0.2
# for facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
