#!/bin/bash

# Name of the private key
private_key="school"

# Number of bits in the created key
key_bits=4096

# Passphrase to protect the key
passphrase="betty"

# Create RSA key pair
ssh-keygen -t rsa -b "$key_bits" -f "$private_key" -N "$passphrase"

# Display key details
echo "Generating public/private rsa key pair."
echo "Your identification has been saved in $private_key."
echo "Your public key has been saved in $private_key.pub."
echo "The key fingerprint is:"
ssh-keygen -lf "$private_key"
echo "The key's randomart image is:"
ssh-keygen -lvf "$private_key"

# List the files
ls -l "$private_key" "$private_key.pub"
